-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 22:13:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_sinner` DEFAULT CHARACTER SET utf8 ;
USE `database_sinner` ;

-- -----------------------------------------------------
-- Table `database_sinner`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `img` VARCHAR(100) NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuario_tb_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC) ,
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `database_sinner`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`banda` (
  `id_banda` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) NOT NULL,
  `img` VARCHAR(100) NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_banda`),
  INDEX `fk_banda_genero1_idx` (`genero_id_genero` ASC) ,
  CONSTRAINT `fk_banda_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `duracao` CHAR(8) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `img` VARCHAR(100) NULL,
  `banda_id_banda` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `fk_tb_album_tb_banda1_idx` (`banda_id_banda` ASC) ,
  CONSTRAINT `fk_tb_album_tb_banda1`
    FOREIGN KEY (`banda_id_banda`)
    REFERENCES `database_sinner`.`banda` (`id_banda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`musica` (
  `id_musica` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  `duracao` CHAR(8) NOT NULL,
  `musica` VARCHAR(100) NOT NULL,
  `album_id_album` INT NOT NULL,
  PRIMARY KEY (`id_musica`),
  INDEX `fk_tb_musica_tb_album1_idx` (`album_id_album` ASC) ,
  CONSTRAINT `fk_tb_musica_tb_album1`
    FOREIGN KEY (`album_id_album`)
    REFERENCES `database_sinner`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `img` VARCHAR(100) NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_tb_noticia_tb_genero1_idx` (`genero_id_genero` ASC) ,
  CONSTRAINT `fk_tb_noticia_tb_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario_genero` (
  `id_usuario_genero` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `genero_id_genero` INT NOT NULL,
  INDEX `fk_usuario_has_genero_genero1_idx` (`genero_id_genero` ASC) ,
  INDEX `fk_usuario_has_genero_usuario1_idx` (`usuario_id_usuario` ASC) ,
  PRIMARY KEY (`id_usuario_genero`),
  CONSTRAINT `fk_usuario_has_genero_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `database_sinner`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_genero_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO tipo_usuario VALUES(DEFAULT,"ADM");
INSERT INTO tipo_usuario VALUES(DEFAULT,"USER");
INSERT INTO usuario VALUES(DEFAULT, "Matheus", "matheus@gmail.com", "123", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Bruna", "bruna@gmail.com", "1234", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Jonathan", "jonathan@gmail.com", "12345", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Lucas", "lucas@gmail.com", "123", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "usuario", "usuario@gmail.com", "123", NULL, 2);
INSERT INTO genero VALUES(DEFAULT, "Eletrônica");
INSERT INTO genero VALUES(DEFAULT, "Pop");
INSERT INTO genero VALUES(DEFAULT, "Heavy Metal");
INSERT INTO genero VALUES(DEFAULT, "Indie");
INSERT INTO genero VALUES(DEFAULT, "Rock");
INSERT INTO banda VALUES(DEFAULT, "Pegboard Nerds", "../../../../Sinner-SA/SA-Sinner/css/images/image01pegboardnerds.jpg", 1);
INSERT INTO banda VALUES(DEFAULT, "Iron Maiden", "../../../../Sinner-SA/SA-Sinner/css/images/image02ironmaiden.jpg", 2);
INSERT INTO banda VALUES(DEFAULT, "Cage the Elephant", "../../../../Sinner-SA/SA-Sinner/css/images/image03cagetheelephant.png", 3);
INSERT INTO banda VALUES(DEFAULT, "Pink Floyd", "../../../../Sinner-SA/SA-Sinner/css/images/image04pinkfloyd.jpg", 4);
INSERT INTO banda VALUES(DEFAULT, "Red Hot Chili Peppers", "../../../../Sinner-SA/SA-Sinner/css/images/logo_rhcp.png", 5);
INSERT INTO banda VALUES(DEFAULT, "Jack Stauber", "../../../../Sinner-SA/SA-Sinner/css/images/jack_stauber_logo.jpg", 6);
INSERT INTO banda VALUES(DEFAULT, "System of a Down", "../../../../Sinner-SA/SA-Sinner/css/images/soad_logo.jpg", 7);
INSERT INTO banda VALUES(DEFAULT, "Chopin", "../../../../Sinner-SA/SA-Sinner/css/images/chopin_logo.jpg", 8);	
	
INSERT INTO album VALUES(DEFAULT, "04:23", "Swamp Thing", "../../../../Sinner-SA/SA-Sinner/css/images/image05swampthing.jpg" , 1);
INSERT INTO album VALUES(DEFAULT, "39:11", "The Number of the Beast", "../../../../Sinner-SA/SA-Sinner/css/images/image06numberofthebeast.jpg" , 2);
INSERT INTO album VALUES(DEFAULT, "37:23", "Melophobia", "../../../../Sinner-SA/SA-Sinner/css/images/image07melophobia.jpg" , 3);
INSERT INTO album VALUES(DEFAULT, "81:09", "The Wall", "../../../../Sinner-SA/SA-Sinner/css/images/image08thewall.jpg" , 4);
INSERT INTO album VALUES(DEFAULT, "100:19", "Preludes", "../../../../Sinner-SA/SA-Sinner/css/images/preludes.jpg" , 5);
INSERT INTO album VALUES(DEFAULT, "62:11", "Pop food", "../../../../Sinner-SA/SA-Sinner/css/images/popfood.jpg" , 6);
INSERT INTO album VALUES(DEFAULT, "78:03", "I'm With You", "../../../../Sinner-SA/SA-Sinner/css/images/gateway.jpg" , 7);
INSERT INTO album VALUES(DEFAULT, "81:09", "Toxicity", "../../../../Sinner-SA/SA-Sinner/css/images/toxicity.jpg" , 8);


INSERT INTO musica VALUES(DEFAULT, "Swamp Thing", "04:23", "../../../../Sinner-SA/SA-Sinner/css/music/swampthing.mp3", 1);
INSERT INTO musica VALUES(DEFAULT, "The Number of the Beast", "04:52", "../../../../Sinner-SA/SA-Sinner/css/music/thenumberofthebeast.mp3", 2);
INSERT INTO musica VALUES(DEFAULT, "Telescope", "03:56", "../../../../Sinner-SA/SA-Sinner/css/music/telescope.mp3", 3);
INSERT INTO musica VALUES(DEFAULT, "Hey You", "04:40", "../../../../Sinner-SA/SA-Sinner/css/music/heyyou.mp3", 4);

INSERT INTO musica VALUES(DEFAULT, "Prision Song", "03:21", "../../../../Sinner-SA/SA-Sinner/css/music/soad1.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Needles", "03:13", "../../../../Sinner-SA/SA-Sinner/css/music/soad2.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Deer Dance", "02:55", "../../../../Sinner-SA/SA-Sinner/css/music/soad3.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Jer Pilot", "02:06", "../../../../Sinner-SA/SA-Sinner/css/music/soad4.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "X", "01:58", "../../../../Sinner-SA/SA-Sinner/css/music/soad5.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Chop Suey!", "03:30", "../../../../Sinner-SA/SA-Sinner/css/music/soad6.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Bounce", "01:54", "../../../../Sinner-SA/SA-Sinner/css/music/soad7.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Forest", "00:04:00", "../../../../Sinner-SA/SA-Sinner/css/music/soad8.mp3", 8);
INSERT INTO musica VALUES(DEFAULT, "Toxicity", "00:04:40", "../../../../Sinner-SA/SA-Sinner/css/music/soad12.mp3", 8);

INSERT INTO musica VALUES(DEFAULT, "Monarchy of Roses", "04:12", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp1.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Factory Of Faith", "04:21", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp2.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Brendan's Death Song", "05:39", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp3.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Ethiopia", "03:51", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp4.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Annie Wants a Baby", "03:40", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp5.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Look Around", "03:28", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp6.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "The Adventures Of Rain", "04:43", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp7.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Did I Let You Know?", "04:22", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp8.mp3", 7);
INSERT INTO musica VALUES(DEFAULT, "Goodbye Hooray", "03:53", "../../../../Sinner-SA/SA-Sinner/css/music/rhcp9.mp3", 7);

INSERT INTO musica VALUES(DEFAULT, "Buttercup", "03:28", "../../../../Sinner-SA/SA-Sinner/css/music/pf1.mp3", 6);
INSERT INTO musica VALUES(DEFAULT, "oh klahoma", "03:08", "../../../../Sinner-SA/SA-Sinner/css/music/pf2.mp3", 6);

INSERT INTO musica VALUES(DEFAULT, "claire de lune", "05:01", "../../../../Sinner-SA/SA-Sinner/css/music/cp1.mp3", 5);
INSERT INTO musica VALUES(DEFAULT, "Etude", "02:21", "../../../../Sinner-SA/SA-Sinner/css/music/cp2.mp3", 5);
INSERT INTO musica VALUES(DEFAULT, "nocturne piano & violino", "03:21", "../../../../Sinner-SA/SA-Sinner/css/music/cp3.mp3", 5);
INSERT INTO musica VALUES(DEFAULT, "nocture", "04:29", "../../../../Sinner-SA/SA-Sinner/css/music/cp4.mp3", 5);
INSERT INTO musica VALUES(DEFAULT, "Romantic ", "05:13", "../../../../Sinner-SA/SA-Sinner/css/music/cp5.mp3", 5);
INSERT INTO musica VALUES(DEFAULT, "Spring Waltz", "05:11", "../../../../Sinner-SA/SA-Sinner/css/music/cp6.mp3", 5);



INSERT INTO noticia VALUES(DEFAULT, "Vocalista sofre acidente", "<div>Roger Waters, ex-líder do Pink Floyd, começa nesta terça-feira (9) em São Paulo uma sequência de shows em sete cidades no Brasil (veja informações no fim do texto). O cantor inglês de 75 anos apresenta sua turnê  Us   Them.</div><div style='text-align: left;'><font face='Courier'>como é o show?</font></div><div>Ele junta músicas de sua carreira solo com as canções do Pink Floyd. Segundo o cantor, 80% do show será de álbuns antigos e 20% será de novidades. 'Mas tudo será conectado por um tema geral. Será espetacular como todos os meus shows foram', contou Waters</div><div><div>Waters falará algo sobre o Brasil?</div><div>É provável que sim: ele é bem informado. Quando esteve por aqui em 2012, fez uma homenagem ao brasileiro Jean Charles de Menezes, morto por policiais britânicos em Londres, em 2005, ao ser confundido com um terrorista. 'Gostaria de dedicar este concerto a Jean Charles, sua família e sua luta por verdade e justiça'.</div><div><br></div><div>Ele vai fazer alguma menção a políticos brasileiros?</div><div>Levando em conta o histórico da turnê, é possível que sim. Quando fez shows nos EUA, em 2017, fez várias referências ao presidente Donald Trump: em uma delas, a frase 'Trump é um porco' aparecia escrita no telão. Na Europa, usou um vídeo para criticar Trump, Putin, e líderes europeus como Theresa May e Emmanuel Macron.</div><div><br></div><div>'Eu adoraria fazer um show diferente para cada lugar, sobre cada problema local, político, discriminação, mas é impossível. Confesso que não tinha pensado na América do Sul ainda', disse para jornalistas brasileiros em dezembro do ano passado.</div></div>", "../../../../Sinner-SA/SA-Sinner/css/images/image08thewall.jpg", 3);
INSERT INTO noticia VALUES(DEFAULT, "Vocalista muda de banda", "Ocorreu uma mudança de bana", "../../../../Sinner-SA/SA-Sinner/css/images/image04pinkfloyd.jpg", 4);
INSERT INTO noticia VALUES(DEFAULT, "Rock in Rio", "Iron Maiden toca no Rock in Rio", "../../../../Sinner-SA/SA-Sinner/css/images/image02ironmaiden.jpg", 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 1);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 3);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 4);
INSERT INTO usuario_genero VALUES(DEFAULT, 2, 3);
INSERT INTO usuario_genero VALUES(DEFAULT, 3, 1);
INSERT INTO usuario_genero VALUES(DEFAULT, 3, 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 4, 4);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
