-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 22:13:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_sinner` DEFAULT CHARACTER SET utf8 ;
USE `database_sinner` ;

-- -----------------------------------------------------
-- Table `database_sinner`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `img` VARCHAR(100) NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuario_tb_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC) ,
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `database_sinner`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`banda` (
  `id_banda` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) NOT NULL,
  `img` VARCHAR(100) NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_banda`),
  INDEX `fk_banda_genero1_idx` (`genero_id_genero` ASC) ,
  CONSTRAINT `fk_banda_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `duracao` CHAR(8) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `img` VARCHAR(100) NULL,
  `banda_id_banda` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `fk_tb_album_tb_banda1_idx` (`banda_id_banda` ASC) ,
  CONSTRAINT `fk_tb_album_tb_banda1`
    FOREIGN KEY (`banda_id_banda`)
    REFERENCES `database_sinner`.`banda` (`id_banda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`musica` (
  `id_musica` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  `duracao` CHAR(8) NOT NULL,
  `musica` VARCHAR(100) NOT NULL,
  `album_id_album` INT NOT NULL,
  PRIMARY KEY (`id_musica`),
  INDEX `fk_tb_musica_tb_album1_idx` (`album_id_album` ASC) ,
  CONSTRAINT `fk_tb_musica_tb_album1`
    FOREIGN KEY (`album_id_album`)
    REFERENCES `database_sinner`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `conteudo` MEDIUMTEXT NOT NULL,
  `img` VARCHAR(100) NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_tb_noticia_tb_genero1_idx` (`genero_id_genero` ASC) ,
  CONSTRAINT `fk_tb_noticia_tb_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario_genero` (
  `id_usuario_genero` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `genero_id_genero` INT NOT NULL,
  INDEX `fk_usuario_has_genero_genero1_idx` (`genero_id_genero` ASC) ,
  INDEX `fk_usuario_has_genero_usuario1_idx` (`usuario_id_usuario` ASC) ,
  PRIMARY KEY (`id_usuario_genero`),
  CONSTRAINT `fk_usuario_has_genero_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `database_sinner`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_genero_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO tipo_usuario VALUES(DEFAULT,"ADM");
INSERT INTO tipo_usuario VALUES(DEFAULT,"USER");
INSERT INTO usuario VALUES(DEFAULT, "Matheus", "matheus@gmail.com", "123", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Bruna", "bruna@gmail.com", "1234", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Jonathan", "jonathan@gmail.com", "12345", NULL, 1);
INSERT INTO usuario VALUES(DEFAULT, "Lucas", "lucas@gmail.com", "123", NULL, 1);
INSERT INTO genero VALUES(DEFAULT, "Eletrônica");
INSERT INTO genero VALUES(DEFAULT, "Heavy Metal");
INSERT INTO genero VALUES(DEFAULT, "Indie");
INSERT INTO genero VALUES(DEFAULT, "Rock");
INSERT INTO banda VALUES(DEFAULT, "Pegboard Nerds", "../../../../Sinner-SA/SA-Sinner/css/images/image01pegboardnerds.jpg", 1);
INSERT INTO banda VALUES(DEFAULT, "Iron Maiden", "../../../../Sinner-SA/SA-Sinner/css/images/image02ironmaiden.jpg", 2);
INSERT INTO banda VALUES(DEFAULT, "Cage the Elephant", "../../../../Sinner-SA/SA-Sinner/css/images/image03cagetheelephant.png", 3);
INSERT INTO banda VALUES(DEFAULT, "Pink Floyd", "../../../../Sinner-SA/SA-Sinner/css/images/image04pinkfloyd.jpg", 4);
INSERT INTO album VALUES(DEFAULT, "00:04:23", "Swamp Thing", "../../../../Sinner-SA/SA-Sinner/css/images/image05swampthing.jpg" , 1);
INSERT INTO album VALUES(DEFAULT, "00:39:11", "The Number of the Beast", "../../../../Sinner-SA/SA-Sinner/css/images/image06numberofthebeast.jpg" , 2);
INSERT INTO album VALUES(DEFAULT, "00:37:23", "Melophobia", "../../../../Sinner-SA/SA-Sinner/css/images/image07melophobia.jpg" , 3);
INSERT INTO album VALUES(DEFAULT, "00:81:09", "The Wall", "../../../../Sinner-SA/SA-Sinner/css/images/image08thewall.jpg" , 4);
INSERT INTO musica VALUES(DEFAULT, "Swamp Thing", "00:04:23", "../../css/music/swampthing.mp3", 1);
INSERT INTO musica VALUES(DEFAULT, "The Number of the Beast", "00:04:52", "../../css/music/thenumberofthebeast.mp3", 2);
INSERT INTO musica VALUES(DEFAULT, "Telescope", "00:03:56", "../../css/music/telescope.mp3", 3);
INSERT INTO musica VALUES(DEFAULT, "Hey You", "00:04:40", "../../css/music/heyyou.mp3", 4);
INSERT INTO noticia VALUES(DEFAULT, "Vocalista sofre acidente", "Ocorreu um acidente automobilistico", "../../../../Sinner-SA/SA-Sinner/css/images/image08thewall.jpg", 3);
INSERT INTO noticia VALUES(DEFAULT, "Vocalista muda de banda", "Ocorreu uma mudança de bana", "../../../../Sinner-SA/SA-Sinner/css/images/image04pinkfloyd.jpg", 4);
INSERT INTO noticia VALUES(DEFAULT, "Rock in Rio", "Iron Maiden toca no Rock in Rio", "../../../../Sinner-SA/SA-Sinner/css/images/image02ironmaiden.jpg", 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 1);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 3);
INSERT INTO usuario_genero VALUES(DEFAULT, 1, 4);
INSERT INTO usuario_genero VALUES(DEFAULT, 2, 3);
INSERT INTO usuario_genero VALUES(DEFAULT, 3, 1);
INSERT INTO usuario_genero VALUES(DEFAULT, 3, 2);
INSERT INTO usuario_genero VALUES(DEFAULT, 4, 4);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
