-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 19:15:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_sinner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_sinner` DEFAULT CHARACTER SET utf8 ;
USE `database_sinner` ;

-- -----------------------------------------------------
-- Table `database_sinner`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `img` VARCHAR(100) NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuario_tb_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC),
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `database_sinner`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`banda` (
  `id_banda` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) NOT NULL,
  `img` VARCHAR(100) NULL,
  PRIMARY KEY (`id_banda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`usuario_banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`usuario_banda` (
  `id_usuario_banda` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `banda_id_banda` INT NOT NULL,
  PRIMARY KEY (`id_usuario_banda`),
  INDEX `fk_tb_usuario_banda_tb_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_tb_usuario_banda_tb_banda1_idx` (`banda_id_banda` ASC),
  CONSTRAINT `fk_tb_usuario_banda_tb_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `database_sinner`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_banda_tb_banda1`
    FOREIGN KEY (`banda_id_banda`)
    REFERENCES `database_sinner`.`banda` (`id_banda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `duracao` CHAR(8) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `img` VARCHAR(100) NULL,
  `banda_id_banda` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `fk_tb_album_tb_banda1_idx` (`banda_id_banda` ASC),
  CONSTRAINT `fk_tb_album_tb_banda1`
    FOREIGN KEY (`banda_id_banda`)
    REFERENCES `database_sinner`.`banda` (`id_banda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`genero` (
  `id_genero` INT NOT NULL,
  `descricao` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`musica` (
  `id_musica` INT NOT NULL,
  `dsmusica` VARCHAR(30) NOT NULL,
  `duracao` CHAR(8) NOT NULL,
  `musica` VARCHAR(100) NOT NULL,
  `album_id_album` INT NOT NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_musica`),
  INDEX `fk_tb_musica_tb_album1_idx` (`album_id_album` ASC),
  INDEX `fk_tb_musica_tb_genero1_idx` (`genero_id_genero` ASC),
  CONSTRAINT `fk_tb_musica_tb_album1`
    FOREIGN KEY (`album_id_album`)
    REFERENCES `database_sinner`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_musica_tb_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_sinner`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_sinner`.`noticia` (
  `id_noticia` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `conteudo` MEDIUMTEXT NOT NULL,
  `img` VARCHAR(100) NULL,
  `genero_id_genero` INT NOT NULL,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_tb_noticia_tb_genero1_idx` (`genero_id_genero` ASC),
  CONSTRAINT `fk_tb_noticia_tb_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `database_sinner`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
